name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with: 
        node-version: '12'
        
    - name: Build and push Docker image
      run: |
        docker build -t dummy-server .
        docker tag dummy-server:latest ${{ secrets.DOCKER_REPO_URL }}/sanvalero:dummy-server
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_REPO_URL }}/sanvalero:dummy-server

    - name: SSH into EC2 instance and deploy
      uses: actions/checkout@v2 
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.MY_EC2_SSH_KEY }}
        
        run: |
          sudo echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          sudo ssh -o StrictHostKeyChecking=no -i private_key ubuntu@54.75.220.108 '

              # Now we have got the access of EC2 and we will start the deploy .
              sudo docker pull ${{ secrets.DOCKER_REPO_URL }}/sanvalero:dummy-server
              sudo docker stop my-node-app || true
              sudo docker rm my-node-app || true
              sudo docker run -d -p 3000:3000 --name my-node-app ${{ secrets.DOCKER_REPO_URL }}/sanvalero:dummy-server
              '

