name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.MY_EC2_SSH_KEY }}
            HOSTNAME: 54.75.220.108
            USER_NAME: ${{secrets.EC2_USERNAME}}
      
        run: |
          sudo echo "$MY_EC2_SSH_KEY" > private_key.pem && chmod 777 private_key.pem
          sudo ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy
              cd /home/ubuntu/
              '
  
